[build]
  functions = "netlify/functions"
  command = "npm install axios form-data"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[functions]]
  node_bundler = "esbuild"
  timeout = 30  # Max allowed timeout
  [functions.convert]
    included_files = ["netlify/functions/convert.js"]
